--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Pedhot-Dev/DeathEffect
build-by-default: true
branches:
- master
projects:
  DeathEffect:
    path: ""
    libs:
      - src: Ifera/ConfigUpdater/ConfigUpdater
        version: ^1.1.0
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
...
